"""Stack Composer — generate Terraform HCL from a stack definition.

A stack definition describes a set of registry modules with variable
bindings and dependency ordering. This service renders that definition
into concrete HCL files (main.tf, variables.tf, outputs.tf).
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)

REGISTRY_PROTOCOL_BASE = "powerops.tonytechlab.com"


# ---------------------------------------------------------------------------
# Result types
# ---------------------------------------------------------------------------

@dataclass
class UpgradeInfo:
    module_name: str
    current_version: str
    latest_version: str
    source: str


@dataclass
class ComposeResult:
    project_id: str
    generated_files: dict[str, str] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Composer
# ---------------------------------------------------------------------------

class StackComposer:
    """Renders a stack definition into HCL files."""

    async def compose_project(
        self,
        session: AsyncSession,
        project_id: str,
        stack_definition: dict[str, Any],
        workspace_dir: Path,
        registry_url: str = REGISTRY_PROTOCOL_BASE,
    ) -> ComposeResult:
        """Generate main.tf, variables.tf, outputs.tf in workspace_dir."""
        result = ComposeResult(project_id=project_id)
        modules: list[dict] = stack_definition.get("modules", [])
        variables: list[dict] = stack_definition.get("variables", [])

        warnings = self.validate_stack_dependencies(modules)
        result.warnings.extend(warnings)

        main_tf = self._generate_main_tf(modules, registry_url)
        variables_tf = self._generate_variables_tf(variables)
        outputs_tf = self._generate_outputs_tf(modules)

        result.generated_files["main.tf"] = main_tf
        result.generated_files["variables.tf"] = variables_tf
        result.generated_files["outputs.tf"] = outputs_tf

        # Persist files to disk if workspace_dir is provided
        if workspace_dir:
            workspace_dir.mkdir(parents=True, exist_ok=True)
            for filename, content in result.generated_files.items():
                (workspace_dir / filename).write_text(content, encoding="utf-8")
            logger.info("Stack composed to %s (%d modules)", workspace_dir, len(modules))

        return result

    def generate_module_block(self, module_def: dict, registry_url: str) -> str:
        """Render a single HCL module block."""
        name = module_def["name"]
        source = module_def["source"]   # e.g. "powerops/aws-vpc/aws"
        version = module_def.get("version", "")
        variables: dict[str, str] = module_def.get("variables", {})
        depends_on: list[str] = module_def.get("depends_on", [])

        lines = [f'module "{name}" {{']
        lines.append(f'  source  = "{registry_url}/{source}"')
        if version:
            lines.append(f'  version = "{version}"')
        lines.append("")
        for var_name, var_val in variables.items():
            lines.append(f"  {var_name} = {var_val}")
        if depends_on:
            refs = ", ".join(f"module.{d}" for d in depends_on)
            lines.append(f"\n  depends_on = [{refs}]")
        lines.append("}")
        return "\n".join(lines)

    def _generate_main_tf(self, modules: list[dict], registry_url: str) -> str:
        header = (
            "# Generated by PowerOps Stack Composer\n"
            "# Do not edit manually — regenerate via the stack composer.\n\n"
            f'terraform {{\n  required_version = ">= 1.0"\n}}\n'
        )
        blocks = [self.generate_module_block(m, registry_url) for m in modules]
        return header + "\n\n".join(blocks) + "\n"

    def generate_variables_tf(self, variables: list[dict]) -> str:
        return self._generate_variables_tf(variables)

    def _generate_variables_tf(self, variables: list[dict]) -> str:
        if not variables:
            return "# No top-level variables defined for this stack.\n"
        lines = ["# Stack input variables — generated by PowerOps Stack Composer\n"]
        for v in variables:
            lines.append(f'variable "{v["name"]}" {{')
            lines.append(f'  type        = {v.get("type", "string")}')
            desc = v.get("description", "")
            if desc:
                lines.append(f'  description = "{desc}"')
            default = v.get("default")
            if default is not None:
                lines.append(f'  default     = {json.dumps(default)}')
            lines.append("}\n")
        return "\n".join(lines)

    def generate_outputs_tf(self, modules: list[dict]) -> str:
        return self._generate_outputs_tf(modules)

    def _generate_outputs_tf(self, modules: list[dict]) -> str:
        lines = ["# Stack outputs — generated by PowerOps Stack Composer\n"]
        for m in modules:
            name = m["name"]
            lines.append(f'output "{name}_outputs" {{')
            lines.append(f'  value       = module.{name}')
            lines.append(f'  description = "All outputs from module {name}"')
            lines.append("}\n")
        return "\n".join(lines) if len(lines) > 1 else "# No modules defined.\n"

    def validate_stack_dependencies(self, modules: list[dict]) -> list[str]:
        """Check for undefined or circular dependencies. Returns warning strings."""
        warnings: list[str] = []
        names = {m["name"] for m in modules}

        for m in modules:
            for dep in m.get("depends_on", []):
                if dep not in names:
                    warnings.append(
                        f"Module '{m['name']}' depends on '{dep}' which is not in the stack"
                    )

        # Detect circular deps via DFS
        graph: dict[str, list[str]] = {m["name"]: m.get("depends_on", []) for m in modules}
        visited: set[str] = set()
        rec_stack: set[str] = set()

        def has_cycle(node: str) -> bool:
            visited.add(node)
            rec_stack.add(node)
            for neighbour in graph.get(node, []):
                if neighbour not in visited:
                    if has_cycle(neighbour):
                        return True
                elif neighbour in rec_stack:
                    return True
            rec_stack.discard(node)
            return False

        for node in list(graph):
            if node not in visited:
                if has_cycle(node):
                    warnings.append(f"Circular dependency detected involving module '{node}'")
                    break

        return warnings

    async def check_upgrades(
        self, session: AsyncSession, stack_definition: dict[str, Any], org_id: str
    ) -> list[UpgradeInfo]:
        """Check which pinned module versions have newer releases available."""
        from sqlalchemy import select
        from backend.db.models import RegistryModule, RegistryModuleVersion  # type: ignore[attr-defined]

        upgrades: list[UpgradeInfo] = []
        for m in stack_definition.get("modules", []):
            source_parts = m.get("source", "").split("/")
            if len(source_parts) < 3:
                continue
            namespace, name, provider = source_parts[0], source_parts[1], source_parts[2]
            current = m.get("version", "")

            module_row = (await session.execute(
                select(RegistryModule).where(
                    RegistryModule.org_id == org_id,
                    RegistryModule.namespace == namespace,
                    RegistryModule.name == name,
                    RegistryModule.provider == provider,
                )
            )).scalar_one_or_none()
            if not module_row:
                continue

            versions = (await session.execute(
                select(RegistryModuleVersion)
                .where(
                    RegistryModuleVersion.module_id == module_row.id,
                    RegistryModuleVersion.is_deprecated == False,  # noqa: E712
                )
                .order_by(RegistryModuleVersion.published_at.desc())
            )).scalars().all()

            if versions and versions[0].version != current:
                upgrades.append(UpgradeInfo(
                    module_name=m["name"],
                    current_version=current,
                    latest_version=versions[0].version,
                    source=m["source"],
                ))
        return upgrades
